package uwbuilder.underworld.characterbuilder

import android.annotation.SuppressLint
import android.content.Context
import android.content.Intent
import android.content.SharedPreferences
import android.os.Bundle
import android.widget.Button
import android.widget.ImageButton
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity

class ProfilesPopup : AppCompatActivity() {

    private val profile1 = "Profile 1"
    private val profile2 = "Profile 2"
    private val profile3 = "Profile 3"
    private val profile4 = "Profile 4"
    private val profile5 = "Profile 5"
    private val profile6 = "Profile 6"
    private val profile7 = "Profile 7"
    private val profile8 = "Profile 8"
    private val profile9 = "Profile 9"
    private val profile10 = "Profile 10"

    @SuppressLint("SetTextI18n", "CommitPrefEdits")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        overridePendingTransition(0, 0)
        setContentView(R.layout.profiles_popup)

        //Shared Preference Files
        val sharedPreferences1 = this.getSharedPreferences(profile1, Context.MODE_PRIVATE)
        val sharedPreferences2 = this.getSharedPreferences(profile2, Context.MODE_PRIVATE)
        val sharedPreferences3 = this.getSharedPreferences(profile3, Context.MODE_PRIVATE)
        val sharedPreferences4 = this.getSharedPreferences(profile4, Context.MODE_PRIVATE)
        val sharedPreferences5 = this.getSharedPreferences(profile5, Context.MODE_PRIVATE)
        val sharedPreferences6 = this.getSharedPreferences(profile6, Context.MODE_PRIVATE)
        val sharedPreferences7 = this.getSharedPreferences(profile7, Context.MODE_PRIVATE)
        val sharedPreferences8 = this.getSharedPreferences(profile8, Context.MODE_PRIVATE)
        val sharedPreferences9 = this.getSharedPreferences(profile9, Context.MODE_PRIVATE)
        val sharedPreferences10 = this.getSharedPreferences(profile10, Context.MODE_PRIVATE)

        //Page Views
        val profile1Name = findViewById<TextView>(R.id.profile1Name)
        val profile2Name = findViewById<TextView>(R.id.profile2Name)
        val profile3Name = findViewById<TextView>(R.id.profile3Name)
        val profile4Name = findViewById<TextView>(R.id.profile4Name)
        val profile5Name = findViewById<TextView>(R.id.profile5Name)
        val profile6Name = findViewById<TextView>(R.id.profile6Name)
        val profile7Name = findViewById<TextView>(R.id.profile7Name)
        val profile8Name = findViewById<TextView>(R.id.profile8Name)
        val profile9Name = findViewById<TextView>(R.id.profile9Name)
        val profile10Name = findViewById<TextView>(R.id.profile10Name)

        var sharedcharacterRace1 = sharedPreferences1.getString("characterRace", "Race")
        var sharedcharacterClass1 = sharedPreferences1.getString("characterClass", "Class")
        var sharedcharacterVocation1 = sharedPreferences1.getString("characterVocation", "Vocation")
        var sharedblanketsInt1 = sharedPreferences1.getInt("blanketsInt", 0)
        if (sharedcharacterVocation1 != "Vocation"){
            profile1Name.text = "$sharedcharacterRace1\n$sharedcharacterVocation1\n$sharedblanketsInt1 Blankets"
        }
        else{
            profile1Name.text = "$sharedcharacterRace1\n$sharedcharacterClass1\n$sharedblanketsInt1 Blankets"
        }

        var sharedcharacterRace2 = sharedPreferences2.getString("characterRace", "Race")
        var sharedcharacterClass2 = sharedPreferences2.getString("characterClass", "Class")
        var sharedcharacterVocation2 = sharedPreferences2.getString("characterVocation", "Vocation")
        var sharedblanketsInt2 = sharedPreferences2.getInt("blanketsInt", 0)
        if (sharedcharacterVocation2 != "Vocation"){
            profile2Name.text = "$sharedcharacterRace2\n$sharedcharacterVocation2\n$sharedblanketsInt2 Blankets"
        }
        else{
            profile2Name.text = "$sharedcharacterRace2\n$sharedcharacterClass2\n$sharedblanketsInt2 Blankets"
        }

        val profile1Save = findViewById<Button>(R.id.profile1Save)
        val profile2Save = findViewById<Button>(R.id.profile2Save)
        val profile3Save = findViewById<Button>(R.id.profile3Save)
        val profile4Save = findViewById<Button>(R.id.profile4Save)
        val profile5Save = findViewById<Button>(R.id.profile5Save)
        val profile6Save = findViewById<Button>(R.id.profile6Save)
        val profile7Save = findViewById<Button>(R.id.profile7Save)
        val profile8Save = findViewById<Button>(R.id.profile8Save)
        val profile9Save = findViewById<Button>(R.id.profile9Save)
        val profile10Save = findViewById<Button>(R.id.profile10Save)

        val profile1Load = findViewById<Button>(R.id.profile1Load)
        val profile2Load = findViewById<Button>(R.id.profile2Load)
        val profile3Load = findViewById<Button>(R.id.profile3Load)
        val profile4Load = findViewById<Button>(R.id.profile4Load)
        val profile5Load = findViewById<Button>(R.id.profile5Load)
        val profile6Load = findViewById<Button>(R.id.profile6Load)
        val profile7Load = findViewById<Button>(R.id.profile7Load)
        val profile8Load = findViewById<Button>(R.id.profile8Load)
        val profile9Load = findViewById<Button>(R.id.profile9Load)
        val profile10Load = findViewById<Button>(R.id.profile10Load)

        val profile1Delete = findViewById<ImageButton>(R.id.profile1Delete)
        val profile2Delete = findViewById<ImageButton>(R.id.profile2Delete)
        val profile3Delete = findViewById<ImageButton>(R.id.profile3Delete)
        val profile4Delete = findViewById<ImageButton>(R.id.profile4Delete)
        val profile5Delete = findViewById<ImageButton>(R.id.profile5Delete)
        val profile6Delete = findViewById<ImageButton>(R.id.profile6Delete)
        val profile7Delete = findViewById<ImageButton>(R.id.profile7Delete)
        val profile8Delete = findViewById<ImageButton>(R.id.profile8Delete)
        val profile9Delete = findViewById<ImageButton>(R.id.profile9Delete)
        val profile10Delete = findViewById<ImageButton>(R.id.profile10Delete)

        val closePopup = findViewById<Button>(R.id.closePopup)

        //Character Values
        var characterRace = intent.getStringExtra("characterRace")
        var cultureFragsInt = intent.getIntExtra("cultureFragsInt", 0)
        var characterCulture = intent.getStringExtra("characterCulture")
        var characterClass = intent.getStringExtra("characterClass")
        var characterVocation = intent.getStringExtra("characterVocation")
        var levelInt = intent.getIntExtra("levelInt", 1)
        var hpInt = intent.getIntExtra("hpInt", 0)
        var blanketsInt = intent.getIntExtra("blanketsInt", 0)
        var cpInt = intent.getIntExtra("cpInt", 150)
        var freeInt = intent.getIntExtra("freeInt", 0)
        var characterSpentInt = intent.getIntExtra("characterSpentInt", 0)
        var characterFragsInt = intent.getIntExtra("characterFragsInt", 0)

        //General Skills
        var autoRacialSkill = intent.getStringExtra("autoRacialSkill")
        var racialSkill = intent.getStringExtra("racialSkill")
        var racialSelect = intent.getIntExtra("racialSelect", 0)
        var bodySelect = intent.getIntExtra("bodySelect", 0)
        var strengthSelect = intent.getIntExtra("strengthSelect", 0)
        var level3Skill = intent.getStringExtra("level3Skill")
        var level3Select = intent.getIntExtra("level3Select", 0)
        var level6Skill = intent.getStringExtra("level6Skill")
        var level6Select = intent.getIntExtra("level6Select", 0)
        var level9Skill = intent.getStringExtra("level9Skill")
        var level9Select = intent.getIntExtra("level9Select", 0)
        var level12Skill = intent.getStringExtra("level12Skill")
        var level12Select = intent.getIntExtra("level12Select", 0)
        var trapsmithSelect = intent.getIntExtra("trapsmithSelect", 0)
        var tradesmanSelect = intent.getIntExtra("tradesmanSelect", 0)
        var alchemySelect = intent.getIntExtra("alchemySelect", 0)
        var chemistrySelect = intent.getIntExtra("chemistrySelect", 0)
        var blacksmithingSelect = intent.getIntExtra("blacksmithingSelect", 0)
        var artificeSelect = intent.getIntExtra("artificeSelect", 0)
        var scrollcraftingSelect = intent.getIntExtra("scrollcraftingSelect", 0)
        var coldHandsSelect = intent.getIntExtra("coldHandsSelect", 0)
        var createAlcoholSelect = intent.getIntExtra("createAlcoholSelect", 0)
        var heavyDrinkerSelect = intent.getIntExtra("heavyDrinkerSelect", 0)
        var hindsightSelect = intent.getIntExtra("hindsightSelect", 0)
        var intuitionSelect = intent.getIntExtra("intuitionSelect", 0)
        var lootingSelect = intent.getIntExtra("lootingSelect", 0)
        var paragonSelect = intent.getIntExtra("paragonSelect", 0)
        var possumSelect = intent.getIntExtra("possumSelect", 0)
        var teacherSelect = intent.getIntExtra("teacherSelect", 0)
        //Warrior Skills
        var ambidexteritySelect = intent.getIntExtra("ambidexteritySelect", 0)
        var florentineSelect = intent.getIntExtra("florentineSelect", 0)
        var flurrySelect = intent.getIntExtra("flurrySelect", 0)
        var heavyArmorSelect = intent.getIntExtra("heavyArmorSelect", 0)
        var shieldSelect = intent.getIntExtra("shieldSelect", 0)
        var selfMutilateSelect = intent.getIntExtra("selfMutilateSelect", 0)
        var weapRefocusSelect = intent.getIntExtra("weapRefocusSelect", 0)
        var groupProfMedSelect = intent.getIntExtra("groupProfMedSelect", 0)
        var groupProfLrgSelect = intent.getIntExtra("groupProfLrgSelect", 0)
        var profExoticSelect = intent.getIntExtra("profExoticSelect", 0)
        var groupSpecSelect = intent.getIntExtra("groupSpecSelect", 0)
        var specificSpecSelect = intent.getIntExtra("specificSpecSelect", 0)
        var slayParrySelect = intent.getIntExtra("slayParrySelect", 0)
        var slayParryMstrSelect = intent.getIntExtra("slayParryMstrSelect", 0)
        var battlefieldRepairSelect = intent.getIntExtra("battlefieldRepairSelect", 0)
        var crippleSelect = intent.getIntExtra("crippleSelect", 0)
        var decapitateSelect = intent.getIntExtra("decapitateSelect", 0)
        var dirtEyeSelect = intent.getIntExtra("dirtEyeSelect", 0)
        var tripSelect = intent.getIntExtra("tripSelect", 0)
        var whirlBlowsSelect = intent.getIntExtra("whirlBlowsSelect", 0)
        //Rogue Skills
        var garroteSelect = intent.getIntExtra("garroteSelect", 0)
        var sapSelect = intent.getIntExtra("sapSelect", 0)
        var vitalBlowSelect = intent.getIntExtra("vitalBlowSelect", 0)
        var dodgeSelect = intent.getIntExtra("dodgeSelect", 0)
        var specificCritSelect = intent.getIntExtra("specificCritSelect", 0)
        var groupCritSelect = intent.getIntExtra("groupCritSelect", 0)
        var executeSelect = intent.getIntExtra("executeSelect", 0)
        var executeMstrSelect = intent.getIntExtra("executeMstrSelect", 0)
        var blindfighterSelect = intent.getIntExtra("blindfighterSelect", 0)
        var escapeSelect = intent.getIntExtra("escapeSelect", 0)
        var riposteSelect = intent.getIntExtra("riposteSelect", 0)
        var suckerPunchSelect = intent.getIntExtra("suckerPunchSelect", 0)
        var thievesCantSelect = intent.getIntExtra("thievesCantSelect", 0)
        var tumbleSelect = intent.getIntExtra("tumbleSelect", 0)
        //Scholar Skills
        var mysticismSelect = intent.getIntExtra("mysticismSelect", 0)
        var demAngArtsSelect = intent.getIntExtra("demAngArtsSelect", 0)
        var necroArtsSelect = intent.getIntExtra("necroArtsSelect", 0)
        var anatomySelect = intent.getIntExtra("anatomySelect", 0)
        var firstAidSelect = intent.getIntExtra("firstAidSelect", 0)
        var physicianSelect = intent.getIntExtra("physicianSelect", 0)
        var readWriteSelect = intent.getIntExtra("readWriteSelect", 0)
        var readMagicSelect = intent.getIntExtra("readMagicSelect", 0)
        var rdAdvMagicSelect = intent.getIntExtra("rdAdvMagicSelect", 0)
        var rdRitualMagicSelect = intent.getIntExtra("rdRitualMagicSelect", 0)
        var advRitualSelect = intent.getIntExtra("advRitualSelect", 0)
        var eleAttuneSelect = intent.getIntExtra("eleAttuneSelect", 0)
        var combatWizSelect = intent.getIntExtra("combatWizSelect", 0)
        var harvestSelect = intent.getIntExtra("harvestSelect", 0)
        var morticianSelect = intent.getIntExtra("morticianSelect", 0)
        var refocusSelect = intent.getIntExtra("refocusSelect", 0)
        var spellParrySelect = intent.getIntExtra("spellParrySelect", 0)
        var spellVersSkillSelect = intent.getIntExtra("spellVersSkillSelect", 0)
        var spellSwitchSelect = intent.getIntExtra("spellSwitchSelect", 0)
        var sphereSelect1 = intent.getStringExtra("sphereSelect1")
        var sphereSelect2 = intent.getStringExtra("sphereSelect2")
        var sphereSelect3 = intent.getStringExtra("sphereSelect3")
        var slot1Select = intent.getIntExtra("slot1Select", 0)
        var slot2Select = intent.getIntExtra("slot2Select", 0)
        var slot3Select = intent.getIntExtra("slot3Select", 0)
        var slot4Select = intent.getIntExtra("slot4Select", 0)
        var slot5Select = intent.getIntExtra("slot5Select", 0)
        var slot6Select = intent.getIntExtra("slot6Select", 0)
        var slot7Select = intent.getIntExtra("slot7Select", 0)
        var slot8Select = intent.getIntExtra("slot8Select", 0)
        var slot9Select = intent.getIntExtra("slot9Select", 0)
        var ritualSelect = intent.getIntExtra("ritualSelect", 0)

        //Profile 1
        profile1Save.setOnClickListener() {
            val editor:SharedPreferences.Editor = sharedPreferences1.edit()

            profile1Name.text = "$characterRace\n$characterClass\n$blanketsInt Blankets"

            //Character Values
            editor.putString("characterRace", characterRace)
            editor.putInt("cultureFragsInt", cultureFragsInt)
            println("IN EDITOR CULTURE IS $cultureFragsInt")
            editor.putString("characterCulture", characterCulture)
            editor.putString("characterClass", characterClass)
            println("IN EDITOR CLASS IS $characterClass")
            editor.putString("characterVocation", characterVocation)
            println("IN EDITOR VOCATION IS $characterVocation")
            editor.putInt("levelInt", levelInt)
            editor.putInt("hpInt", hpInt)
            editor.putInt("blanketsInt", blanketsInt)
            editor.putInt("cpInt", cpInt)
            editor.putInt("freeInt", freeInt)
            editor.putInt("characterSpentInt", characterSpentInt)
            editor.putInt("characterFragsInt", characterFragsInt)

            //General Skills
            editor.putString("autoRacialSkill", autoRacialSkill)
            editor.putString("racialSkill", racialSkill)
            editor.putInt("racialSelect", racialSelect)
            editor.putInt("bodySelect", bodySelect)
            editor.putInt("strengthSelect", strengthSelect)
            editor.putString("level3Skill", level3Skill)
            editor.putInt("level3Select", level3Select)
            editor.putString("level6Skill", level6Skill)
            editor.putInt("level6Select", level6Select)
            editor.putString("level9Skill", level9Skill)
            editor.putInt("level9Select", level9Select)
            editor.putString("level12Skill", level12Skill)
            editor.putInt("level12Select", level12Select)
            editor.putInt("trapsmithSelect", trapsmithSelect)
            editor.putInt("tradesmanSelect", tradesmanSelect)
            editor.putInt("alchemySelect", alchemySelect)
            editor.putInt("chemistrySelect", chemistrySelect)
            editor.putInt("blacksmithingSelect", blacksmithingSelect)
            editor.putInt("artificeSelect", artificeSelect)
            editor.putInt("scrollcraftingSelect", scrollcraftingSelect)
            editor.putInt("coldHandsSelect", coldHandsSelect)
            editor.putInt("createAlcoholSelect", createAlcoholSelect)
            editor.putInt("heavyDrinkerSelect", heavyDrinkerSelect)
            editor.putInt("hindsightSelect", hindsightSelect)
            editor.putInt("intuitionSelect", intuitionSelect)
            editor.putInt("lootingSelect", lootingSelect)
            editor.putInt("paragonSelect", paragonSelect)
            editor.putInt("possumSelect", possumSelect)
            editor.putInt("teacherSelect", teacherSelect)
            //Warrior Skills
            editor.putInt("ambidexteritySelect", ambidexteritySelect)
            editor.putInt("florentineSelect", florentineSelect)
            editor.putInt("flurrySelect", flurrySelect)
            editor.putInt("heavyArmorSelect", heavyArmorSelect)
            editor.putInt("shieldSelect", shieldSelect)
            editor.putInt("selfMutilateSelect", selfMutilateSelect)
            editor.putInt("weapRefocusSelect", weapRefocusSelect)
            editor.putInt("groupProfMedSelect", groupProfMedSelect)
            editor.putInt("groupProfLrgSelect", groupProfLrgSelect)
            editor.putInt("profExoticSelect", profExoticSelect)
            editor.putInt("groupSpecSelect", groupSpecSelect)
            editor.putInt("specificSpecSelect", specificSpecSelect)
            editor.putInt("slayParrySelect", slayParrySelect)
            editor.putInt("slayParryMstrSelect", slayParryMstrSelect)
            editor.putInt("battlefieldRepairSelect", battlefieldRepairSelect)
            editor.putInt("crippleSelect", crippleSelect)
            editor.putInt("decapitateSelect", decapitateSelect)
            editor.putInt("dirtEyeSelect", dirtEyeSelect)
            editor.putInt("tripSelect", tripSelect)
            editor.putInt("whirlBlowsSelect", whirlBlowsSelect)
            //Rogue Skills
            editor.putInt("garroteSelect", garroteSelect)
            editor.putInt("sapSelect", sapSelect)
            editor.putInt("vitalBlowSelect", vitalBlowSelect)
            editor.putInt("dodgeSelect", dodgeSelect)
            editor.putInt("specificCritSelect", specificCritSelect)
            editor.putInt("groupCritSelect", groupCritSelect)
            editor.putInt("executeSelect", executeSelect)
            editor.putInt("executeMstrSelect", executeMstrSelect)
            editor.putInt("blindfighterSelect", blindfighterSelect)
            editor.putInt("escapeSelect", escapeSelect)
            editor.putInt("riposteSelect", riposteSelect)
            editor.putInt("suckerPunchSelect", suckerPunchSelect)
            editor.putInt("thievesCantSelect", thievesCantSelect)
            editor.putInt("tumbleSelect", tumbleSelect)
            //Scholar Skills
            editor.putInt("mysticismSelect", mysticismSelect)
            editor.putInt("demAngArtsSelect", demAngArtsSelect)
            editor.putInt("necroArtsSelect", necroArtsSelect)
            editor.putInt("anatomySelect", anatomySelect)
            editor.putInt("firstAidSelect", firstAidSelect)
            editor.putInt("physicianSelect", physicianSelect)
            editor.putInt("readWriteSelect", readWriteSelect)
            editor.putInt("readMagicSelect", readMagicSelect)
            editor.putInt("rdAdvMagicSelect", rdAdvMagicSelect)
            editor.putInt("rdRitualMagicSelect", rdRitualMagicSelect)
            editor.putInt("advRitualSelect", advRitualSelect)
            editor.putInt("eleAttuneSelect", eleAttuneSelect)
            editor.putInt("combatWizSelect", combatWizSelect)
            editor.putInt("harvestSelect", harvestSelect)
            editor.putInt("morticianSelect", morticianSelect)
            editor.putInt("refocusSelect", refocusSelect)
            editor.putInt("spellParrySelect", spellParrySelect)
            editor.putInt("spellVersSkillSelect", spellVersSkillSelect)
            editor.putInt("spellSwitchSelect", spellSwitchSelect)
            editor.putString("sphereSelect1", sphereSelect1)
            println("IN EDITOR SPHERE 1 IS $sphereSelect1")
            editor.putString("sphereSelect2", sphereSelect2)
            editor.putString("sphereSelect3", sphereSelect3)
            editor.putInt("slot1Select", slot1Select)
            editor.putInt("slot2Select", slot2Select)
            editor.putInt("slot3Select", slot3Select)
            editor.putInt("slot4Select", slot4Select)
            editor.putInt("slot5Select", slot5Select)
            editor.putInt("slot6Select", slot6Select)
            editor.putInt("slot7Select", slot7Select)
            editor.putInt("slot8Select", slot8Select)
            editor.putInt("slot9Select", slot9Select)
            editor.putInt("ritualSelect", ritualSelect)

            editor.apply()
            editor.commit()

            sharedcharacterRace1 = sharedPreferences1.getString("characterRace", "Race")
            sharedcharacterClass1 = sharedPreferences1.getString("characterClass", "Class")
            sharedcharacterVocation1 = sharedPreferences1.getString("characterVocation", "Vocation")
            sharedblanketsInt1 = sharedPreferences1.getInt("blanketsInt", 0)
            if (sharedcharacterVocation1 != "Vocation"){
                profile1Name.text = "$sharedcharacterRace1\n$sharedcharacterVocation1\n$sharedblanketsInt1 Blankets"
            }
            else{
                profile1Name.text = "$sharedcharacterRace1\n$sharedcharacterClass1\n$sharedblanketsInt1 Blankets"
            }

        }

        profile1Load.setOnClickListener() {
            //Character Values
            val sharedcharacterRace = sharedPreferences1.getString("characterRace", characterRace)
            val sharedcultureFragsInt = sharedPreferences1.getInt("cultureFragsInt", cultureFragsInt)
            println("IN LOAD CULTURE IS $cultureFragsInt AND SHARED CULTURE IS $sharedcultureFragsInt")
            val sharedcharacterCulture = sharedPreferences1.getString("characterCulture", characterCulture)
            val sharedcharacterClass = sharedPreferences1.getString("characterClass", characterClass)
            println("IN LOAD CLASS IS $characterClass AND SHARED CLASS IS $sharedcharacterClass")
            val sharedcharacterVocation = sharedPreferences1.getString("characterVocation", characterVocation)
            println("IN LOAD VOCATION IS $characterVocation AND SHARED VOCATION IS $sharedcharacterVocation")
            val sharedlevelInt = sharedPreferences1.getInt("levelInt", levelInt)
            val sharedhpInt = sharedPreferences1.getInt("hpInt", hpInt)
            val sharedblanketsInt = sharedPreferences1.getInt("blanketsInt", blanketsInt)
            val sharedcpInt = sharedPreferences1.getInt("cpInt", cpInt)
            val sharedfreeInt = sharedPreferences1.getInt("freeInt", freeInt)
            val sharedcharacterSpentInt = sharedPreferences1.getInt("characterSpentInt", characterSpentInt)
            val sharedcharacterFragsInt = sharedPreferences1.getInt("characterFragsInt", characterFragsInt)

            //General Skills
            val sharedautoRacialSkill = sharedPreferences1.getString("autoRacialSkill", autoRacialSkill)
            val sharedracialSkill = sharedPreferences1.getString("racialSkill", racialSkill)
            val sharedracialSelect = sharedPreferences1.getInt("racialSelect", racialSelect)
            val sharedbodySelect = sharedPreferences1.getInt("bodySelect", bodySelect)
            val sharedstrengthSelect = sharedPreferences1.getInt("strengthSelect", strengthSelect)
            val sharedlevel3Skill = sharedPreferences1.getString("level3Skill", level3Skill)
            val sharedlevel3Select = sharedPreferences1.getInt("level3Select", level3Select)
            val sharedlevel6Skill = sharedPreferences1.getString("level6Skill", level6Skill)
            val sharedlevel6Select = sharedPreferences1.getInt("level6Select", level6Select)
            val sharedlevel9Skill = sharedPreferences1.getString("level9Skill", level9Skill)
            val sharedlevel9Select = sharedPreferences1.getInt("level9Select", level9Select)
            val sharedlevel12Skill = sharedPreferences1.getString("level12Skill", level12Skill)
            val sharedlevel12Select = sharedPreferences1.getInt("level12Select", level12Select)
            val sharedtrapsmithSelect = sharedPreferences1.getInt("trapsmithSelect", trapsmithSelect)
            val sharedtradesmanSelect = sharedPreferences1.getInt("tradesmanSelect", tradesmanSelect)
            val sharedalchemySelect = sharedPreferences1.getInt("alchemySelect", alchemySelect)
            val sharedchemistrySelect = sharedPreferences1.getInt("chemistrySelect", chemistrySelect)
            val sharedblacksmithingSelect = sharedPreferences1.getInt("blacksmithingSelect", blacksmithingSelect)
            val sharedartificeSelect = sharedPreferences1.getInt("artificeSelect", artificeSelect)
            val sharedscrollcraftingSelect = sharedPreferences1.getInt("scrollcraftingSelect", scrollcraftingSelect)
            val sharedcoldHandsSelect = sharedPreferences1.getInt("coldHandsSelect", coldHandsSelect)
            val sharedcreateAlcoholSelect = sharedPreferences1.getInt("createAlcoholSelect", createAlcoholSelect)
            val sharedheavyDrinkerSelect = sharedPreferences1.getInt("heavyDrinkerSelect", heavyDrinkerSelect)
            val sharedhindsightSelect = sharedPreferences1.getInt("hindsightSelect", hindsightSelect)
            val sharedintuitionSelect = sharedPreferences1.getInt("intuitionSelect", intuitionSelect)
            val sharedlootingSelect = sharedPreferences1.getInt("lootingSelect", lootingSelect)
            val sharedparagonSelect = sharedPreferences1.getInt("paragonSelect", paragonSelect)
            val sharedpossumSelect = sharedPreferences1.getInt("possumSelect", possumSelect)
            val sharedteacherSelect = sharedPreferences1.getInt("teacherSelect", teacherSelect)
            //Warrior Skills
            val sharedambidexteritySelect = sharedPreferences1.getInt("ambidexteritySelect", ambidexteritySelect)
            val sharedflorentineSelect = sharedPreferences1.getInt("florentineSelect", florentineSelect)
            val sharedflurrySelect = sharedPreferences1.getInt("flurrySelect", flurrySelect)
            val sharedheavyArmorSelect = sharedPreferences1.getInt("heavyArmorSelect", heavyArmorSelect)
            val sharedshieldSelect = sharedPreferences1.getInt("shieldSelect", shieldSelect)
            val sharedselfMutilateSelect = sharedPreferences1.getInt("selfMutilateSelect", selfMutilateSelect)
            val sharedweapRefocusSelect = sharedPreferences1.getInt("weapRefocusSelect", weapRefocusSelect)
            val sharedgroupProfMedSelect = sharedPreferences1.getInt("groupProfMedSelect", groupProfMedSelect)
            val sharedgroupProfLrgSelect = sharedPreferences1.getInt("groupProfLrgSelect", groupProfLrgSelect)
            val sharedprofExoticSelect = sharedPreferences1.getInt("profExoticSelect", profExoticSelect)
            val sharedgroupSpecSelect = sharedPreferences1.getInt("groupSpecSelect", groupSpecSelect)
            val sharedspecificSpecSelect = sharedPreferences1.getInt("specificSpecSelect", specificSpecSelect)
            val sharedslayParrySelect = sharedPreferences1.getInt("slayParrySelect", slayParrySelect)
            val sharedslayParryMstrSelect = sharedPreferences1.getInt("slayParryMstrSelect", slayParryMstrSelect)
            val sharedbattlefieldRepairSelect = sharedPreferences1.getInt("battlefieldRepairSelect", battlefieldRepairSelect)
            val sharedcrippleSelect = sharedPreferences1.getInt("crippleSelect", crippleSelect)
            val shareddecapitateSelect = sharedPreferences1.getInt("decapitateSelect", decapitateSelect)
            val shareddirtEyeSelect = sharedPreferences1.getInt("dirtEyeSelect", dirtEyeSelect)
            val sharedtripSelect = sharedPreferences1.getInt("tripSelect", tripSelect)
            val sharedwhirlBlowsSelect = sharedPreferences1.getInt("whirlBlowsSelect", whirlBlowsSelect)
            //Rogue Skills
            val sharedgarroteSelect = sharedPreferences1.getInt("garroteSelect", garroteSelect)
            val sharedsapSelect = sharedPreferences1.getInt("sapSelect", sapSelect)
            val sharedvitalBlowSelect = sharedPreferences1.getInt("vitalBlowSelect", vitalBlowSelect)
            val shareddodgeSelect = sharedPreferences1.getInt("dodgeSelect", dodgeSelect)
            val sharedspecificCritSelect = sharedPreferences1.getInt("specificCritSelect", specificCritSelect)
            val sharedgroupCritSelect = sharedPreferences1.getInt("groupCritSelect", groupCritSelect)
            val sharedexecuteSelect = sharedPreferences1.getInt("executeSelect", executeSelect)
            val sharedexecuteMstrSelect = sharedPreferences1.getInt("executeMstrSelect", executeMstrSelect)
            val sharedblindfighterSelect = sharedPreferences1.getInt("blindfighterSelect", blindfighterSelect)
            val sharedescapeSelect = sharedPreferences1.getInt("escapeSelect", escapeSelect)
            val sharedriposteSelect = sharedPreferences1.getInt("riposteSelect", riposteSelect)
            val sharedsuckerPunchSelect = sharedPreferences1.getInt("suckerPunchSelect", suckerPunchSelect)
            val sharedthievesCantSelect = sharedPreferences1.getInt("thievesCantSelect", thievesCantSelect)
            val sharedtumbleSelect = sharedPreferences1.getInt("tumbleSelect", tumbleSelect)
            //Scholar Skills
            val sharedmysticismSelect = sharedPreferences1.getInt("mysticismSelect", mysticismSelect)
            val shareddemAngArtsSelect = sharedPreferences1.getInt("demAngArtsSelect", demAngArtsSelect)
            val sharednecroArtsSelect = sharedPreferences1.getInt("necroArtsSelect", necroArtsSelect)
            val sharedanatomySelect = sharedPreferences1.getInt("anatomySelect", anatomySelect)
            val sharedfirstAidSelect = sharedPreferences1.getInt("firstAidSelect", firstAidSelect)
            val sharedphysicianSelect = sharedPreferences1.getInt("physicianSelect", physicianSelect)
            val sharedreadWriteSelect = sharedPreferences1.getInt("readWriteSelect", readWriteSelect)
            val sharedreadMagicSelect = sharedPreferences1.getInt("readMagicSelect", readMagicSelect)
            val sharedrdAdvMagicSelect = sharedPreferences1.getInt("rdAdvMagicSelect", rdAdvMagicSelect)
            val sharedrdRitualMagicSelect = sharedPreferences1.getInt("rdRitualMagicSelect", rdRitualMagicSelect)
            val sharedadvRitualSelect = sharedPreferences1.getInt("advRitualSelect", advRitualSelect)
            val sharedeleAttuneSelect = sharedPreferences1.getInt("eleAttuneSelect", eleAttuneSelect)
            val sharedcombatWizSelect = sharedPreferences1.getInt("combatWizSelect", combatWizSelect)
            val sharedharvestSelect = sharedPreferences1.getInt("harvestSelect", harvestSelect)
            val sharedmorticianSelect = sharedPreferences1.getInt("morticianSelect", morticianSelect)
            val sharedrefocusSelect = sharedPreferences1.getInt("refocusSelect", refocusSelect)
            val sharedspellParrySelect = sharedPreferences1.getInt("spellParrySelect", spellParrySelect)
            val sharedspellVersSkillSelect = sharedPreferences1.getInt("spellVersSkillSelect", spellVersSkillSelect)
            val sharedspellSwitchSelect = sharedPreferences1.getInt("spellSwitchSelect", spellSwitchSelect)
            val sharedsphereSelect1 = sharedPreferences1.getString("sphereSelect1", sphereSelect1)
            println("IN LOAD SPHERE IS $sphereSelect1 AND SHARED SPHERE IS $sharedsphereSelect1")
            val sharedsphereSelect2 = sharedPreferences1.getString("sphereSelect2", sphereSelect2)
            val sharedsphereSelect3 = sharedPreferences1.getString("sphereSelect3", sphereSelect3)
            val sharedslot1Select = sharedPreferences1.getInt("slot1Select", slot1Select)
            val sharedslot2Select = sharedPreferences1.getInt("slot2Select", slot2Select)
            val sharedslot3Select = sharedPreferences1.getInt("slot3Select", slot3Select)
            val sharedslot4Select = sharedPreferences1.getInt("slot4Select", slot4Select)
            val sharedslot5Select = sharedPreferences1.getInt("slot5Select", slot5Select)
            val sharedslot6Select = sharedPreferences1.getInt("slot6Select", slot6Select)
            val sharedslot7Select = sharedPreferences1.getInt("slot7Select", slot7Select)
            val sharedslot8Select = sharedPreferences1.getInt("slot8Select", slot8Select)
            val sharedslot9Select = sharedPreferences1.getInt("slot9Select", slot9Select)
            val sharedritualSelect = sharedPreferences1.getInt("ritualSelect", ritualSelect)

            val intent = Intent(this, MainActivity::class.java)
            val load = "true"
            intent.putExtra("load", load)
            intent.putExtra("characterRace", sharedcharacterRace)
            intent.putExtra("characterCulture", sharedcharacterCulture)
            intent.putExtra("cultureFragsInt", sharedcultureFragsInt)
            intent.putExtra("characterClass", sharedcharacterClass)
            intent.putExtra("characterVocation", sharedcharacterVocation)
            intent.putExtra("levelInt", sharedlevelInt)
            intent.putExtra("hpInt", sharedhpInt)
            intent.putExtra("blanketsInt", sharedblanketsInt)
            intent.putExtra("cpInt", sharedcpInt)
            intent.putExtra("freeInt", sharedfreeInt)
            intent.putExtra("characterSpentInt", sharedcharacterSpentInt)
            intent.putExtra("characterFragsInt", sharedcharacterFragsInt)

            //General Skills
            intent.putExtra("level3Skill", sharedlevel3Skill)
            intent.putExtra("level3Select", sharedlevel3Select)
            intent.putExtra("level6Skill", sharedlevel6Skill)
            intent.putExtra("level6Select", sharedlevel6Select)
            intent.putExtra("level9Skill", sharedlevel9Skill)
            intent.putExtra("level9Select", sharedlevel9Select)
            intent.putExtra("level12Skill", sharedlevel12Skill)
            intent.putExtra("level12Select", sharedlevel12Select)
            intent.putExtra("autoRacialSkill", sharedautoRacialSkill)
            intent.putExtra("racialSkill", sharedracialSkill)
            intent.putExtra("racialSelect", sharedracialSelect)
            intent.putExtra("bodySelect", sharedbodySelect)
            intent.putExtra("strengthSelect", sharedstrengthSelect)
            intent.putExtra("trapsmithSelect", sharedtrapsmithSelect)
            intent.putExtra("tradesmanSelect", sharedtradesmanSelect)
            intent.putExtra("alchemySelect", sharedalchemySelect)
            intent.putExtra("chemistrySelect", sharedchemistrySelect)
            intent.putExtra("blacksmithingSelect", sharedblacksmithingSelect)
            intent.putExtra("artificeSelect", sharedartificeSelect)
            intent.putExtra("scrollcraftingSelect", sharedscrollcraftingSelect)
            intent.putExtra("coldHandsSelect", sharedcoldHandsSelect)
            intent.putExtra("createAlcoholSelect", sharedcreateAlcoholSelect)
            intent.putExtra("heavyDrinkerSelect", sharedheavyDrinkerSelect)
            intent.putExtra("hindsightSelect", sharedhindsightSelect)
            intent.putExtra("intuitionSelect", sharedintuitionSelect)
            intent.putExtra("lootingSelect", sharedlootingSelect)
            intent.putExtra("paragonSelect", sharedparagonSelect)
            intent.putExtra("possumSelect", sharedpossumSelect)
            intent.putExtra("teacherSelect", sharedteacherSelect)
            //Warrior Skills
            intent.putExtra("ambidexteritySelect", sharedambidexteritySelect)
            intent.putExtra("florentineSelect", sharedflorentineSelect)
            intent.putExtra("flurrySelect", sharedflurrySelect)
            intent.putExtra("heavyArmorSelect", sharedheavyArmorSelect)
            intent.putExtra("shieldSelect", sharedshieldSelect)
            intent.putExtra("selfMutilateSelect", sharedselfMutilateSelect)
            intent.putExtra("weapRefocusSelect", sharedweapRefocusSelect)
            intent.putExtra("groupProfMedSelect", sharedgroupProfMedSelect)
            intent.putExtra("groupProfLrgSelect", sharedgroupProfLrgSelect)
            intent.putExtra("profExoticSelect", sharedprofExoticSelect)
            intent.putExtra("groupSpecSelect", sharedgroupSpecSelect)
            intent.putExtra("specificSpecSelect", sharedspecificSpecSelect)
            intent.putExtra("slayParrySelect", sharedslayParrySelect)
            intent.putExtra("slayParryMstrSelect", sharedslayParryMstrSelect)
            intent.putExtra("battlefieldRepairSelect", sharedbattlefieldRepairSelect)
            intent.putExtra("crippleSelect", sharedcrippleSelect)
            intent.putExtra("decapitateSelect", shareddecapitateSelect)
            intent.putExtra("dirtEyeSelect", shareddirtEyeSelect)
            intent.putExtra("tripSelect", sharedtripSelect)
            intent.putExtra("whirlBlowsSelect", sharedwhirlBlowsSelect)
            //Rogue Skills
            intent.putExtra("garroteSelect", sharedgarroteSelect)
            intent.putExtra("sapSelect", sharedsapSelect)
            intent.putExtra("vitalBlowSelect", sharedvitalBlowSelect)
            intent.putExtra("dodgeSelect", shareddodgeSelect)
            intent.putExtra("specificCritSelect", sharedspecificCritSelect)
            intent.putExtra("groupCritSelect", sharedgroupCritSelect)
            intent.putExtra("executeSelect", sharedexecuteSelect)
            intent.putExtra("executeMstrSelect", sharedexecuteMstrSelect)
            intent.putExtra("blindfighterSelect", sharedblindfighterSelect)
            intent.putExtra("escapeSelect", sharedescapeSelect)
            intent.putExtra("riposteSelect", sharedriposteSelect)
            intent.putExtra("suckerPunchSelect", sharedsuckerPunchSelect)
            intent.putExtra("thievesCantSelect", sharedthievesCantSelect)
            intent.putExtra("tumbleSelect", sharedtumbleSelect)
            //Scholar Skills
            intent.putExtra("mysticismSelect", sharedmysticismSelect)
            intent.putExtra("demAngArtsSelect", shareddemAngArtsSelect)
            intent.putExtra("necroArtsSelect", sharednecroArtsSelect)
            intent.putExtra("anatomySelect", sharedanatomySelect)
            intent.putExtra("firstAidSelect", sharedfirstAidSelect)
            intent.putExtra("physicianSelect", sharedphysicianSelect)
            intent.putExtra("readWriteSelect", sharedreadWriteSelect)
            intent.putExtra("readMagicSelect", sharedreadMagicSelect)
            intent.putExtra("rdAdvMagicSelect", sharedrdAdvMagicSelect)
            intent.putExtra("rdRitualMagicSelect", sharedrdRitualMagicSelect)
            intent.putExtra("advRitualSelect", sharedadvRitualSelect)
            intent.putExtra("eleAttuneSelect", sharedeleAttuneSelect)
            intent.putExtra("combatWizSelect", sharedcombatWizSelect)
            intent.putExtra("harvestSelect", sharedharvestSelect)
            intent.putExtra("morticianSelect", sharedmorticianSelect)
            intent.putExtra("refocusSelect", sharedrefocusSelect)
            intent.putExtra("spellParrySelect", sharedspellParrySelect)
            intent.putExtra("spellVersSkillSelect", sharedspellVersSkillSelect)
            intent.putExtra("spellSwitchSelect", sharedspellSwitchSelect)
            intent.putExtra("sphereSelect1", sharedsphereSelect1)
            intent.putExtra("sphereSelect2", sharedsphereSelect2)
            intent.putExtra("sphereSelect3", sharedsphereSelect3)
            intent.putExtra("slot1Select", sharedslot1Select)
            intent.putExtra("slot2Select", sharedslot2Select)
            intent.putExtra("slot3Select", sharedslot3Select)
            intent.putExtra("slot4Select", sharedslot4Select)
            intent.putExtra("slot5Select", sharedslot5Select)
            intent.putExtra("slot6Select", sharedslot6Select)
            intent.putExtra("slot7Select", sharedslot7Select)
            intent.putExtra("slot8Select", sharedslot8Select)
            intent.putExtra("slot9Select", sharedslot9Select)
            intent.putExtra("ritualSelect", sharedritualSelect)

            startActivity(intent)
        }

        profile1Delete.setOnClickListener() {
            profile1Name.text = "Race\nClass\n0 Blankets"

            val editor = sharedPreferences1.edit()
            editor.clear()
            editor.apply()
        }

        //Profile 2
        profile2Save.setOnClickListener() {
            profile2Name.text = "$characterRace\n$characterClass\n$blanketsInt Blankets"

            val editor:SharedPreferences.Editor = sharedPreferences2.edit()

            //Character Values
            editor.putString("characterRace", characterRace)
            editor.putInt("cultureFragsInt", cultureFragsInt)
            println("IN EDITOR CULTURE IS $cultureFragsInt")
            editor.putString("characterCulture", characterCulture)
            editor.putString("characterClass", characterClass)
            println("IN EDITOR CLASS IS $characterClass")
            editor.putString("characterVocation", characterVocation)
            println("IN EDITOR VOCATION IS $characterVocation")
            editor.putInt("levelInt", levelInt)
            editor.putInt("hpInt", hpInt)
            editor.putInt("blanketsInt", blanketsInt)
            editor.putInt("cpInt", cpInt)
            editor.putInt("freeInt", freeInt)
            editor.putInt("characterSpentInt", characterSpentInt)
            editor.putInt("characterFragsInt", characterFragsInt)

            //General Skills
            editor.putString("autoRacialSkill", autoRacialSkill)
            editor.putString("racialSkill", racialSkill)
            editor.putInt("racialSelect", racialSelect)
            editor.putInt("bodySelect", bodySelect)
            editor.putInt("strengthSelect", strengthSelect)
            editor.putString("level3Skill", level3Skill)
            editor.putInt("level3Select", level3Select)
            editor.putString("level6Skill", level6Skill)
            editor.putInt("level6Select", level6Select)
            editor.putString("level9Skill", level9Skill)
            editor.putInt("level9Select", level9Select)
            editor.putString("level12Skill", level12Skill)
            editor.putInt("level12Select", level12Select)
            editor.putInt("trapsmithSelect", trapsmithSelect)
            editor.putInt("tradesmanSelect", tradesmanSelect)
            editor.putInt("alchemySelect", alchemySelect)
            editor.putInt("chemistrySelect", chemistrySelect)
            editor.putInt("blacksmithingSelect", blacksmithingSelect)
            editor.putInt("artificeSelect", artificeSelect)
            editor.putInt("scrollcraftingSelect", scrollcraftingSelect)
            editor.putInt("coldHandsSelect", coldHandsSelect)
            editor.putInt("createAlcoholSelect", createAlcoholSelect)
            editor.putInt("heavyDrinkerSelect", heavyDrinkerSelect)
            editor.putInt("hindsightSelect", hindsightSelect)
            editor.putInt("intuitionSelect", intuitionSelect)
            editor.putInt("lootingSelect", lootingSelect)
            editor.putInt("paragonSelect", paragonSelect)
            editor.putInt("possumSelect", possumSelect)
            editor.putInt("teacherSelect", teacherSelect)
            //Warrior Skills
            editor.putInt("ambidexteritySelect", ambidexteritySelect)
            editor.putInt("florentineSelect", florentineSelect)
            editor.putInt("flurrySelect", flurrySelect)
            editor.putInt("heavyArmorSelect", heavyArmorSelect)
            editor.putInt("shieldSelect", shieldSelect)
            editor.putInt("selfMutilateSelect", selfMutilateSelect)
            editor.putInt("weapRefocusSelect", weapRefocusSelect)
            editor.putInt("groupProfMedSelect", groupProfMedSelect)
            editor.putInt("groupProfLrgSelect", groupProfLrgSelect)
            editor.putInt("profExoticSelect", profExoticSelect)
            editor.putInt("groupSpecSelect", groupSpecSelect)
            editor.putInt("specificSpecSelect", specificSpecSelect)
            editor.putInt("slayParrySelect", slayParrySelect)
            editor.putInt("slayParryMstrSelect", slayParryMstrSelect)
            editor.putInt("battlefieldRepairSelect", battlefieldRepairSelect)
            editor.putInt("crippleSelect", crippleSelect)
            editor.putInt("decapitateSelect", decapitateSelect)
            editor.putInt("dirtEyeSelect", dirtEyeSelect)
            editor.putInt("tripSelect", tripSelect)
            editor.putInt("whirlBlowsSelect", whirlBlowsSelect)
            //Rogue Skills
            editor.putInt("garroteSelect", garroteSelect)
            editor.putInt("sapSelect", sapSelect)
            editor.putInt("vitalBlowSelect", vitalBlowSelect)
            editor.putInt("dodgeSelect", dodgeSelect)
            editor.putInt("specificCritSelect", specificCritSelect)
            editor.putInt("groupCritSelect", groupCritSelect)
            editor.putInt("executeSelect", executeSelect)
            editor.putInt("executeMstrSelect", executeMstrSelect)
            editor.putInt("blindfighterSelect", blindfighterSelect)
            editor.putInt("escapeSelect", escapeSelect)
            editor.putInt("riposteSelect", riposteSelect)
            editor.putInt("suckerPunchSelect", suckerPunchSelect)
            editor.putInt("thievesCantSelect", thievesCantSelect)
            editor.putInt("tumbleSelect", tumbleSelect)
            //Scholar Skills
            editor.putInt("mysticismSelect", mysticismSelect)
            editor.putInt("demAngArtsSelect", demAngArtsSelect)
            editor.putInt("necroArtsSelect", necroArtsSelect)
            editor.putInt("anatomySelect", anatomySelect)
            editor.putInt("firstAidSelect", firstAidSelect)
            editor.putInt("physicianSelect", physicianSelect)
            editor.putInt("readWriteSelect", readWriteSelect)
            editor.putInt("readMagicSelect", readMagicSelect)
            editor.putInt("rdAdvMagicSelect", rdAdvMagicSelect)
            editor.putInt("rdRitualMagicSelect", rdRitualMagicSelect)
            editor.putInt("advRitualSelect", advRitualSelect)
            editor.putInt("eleAttuneSelect", eleAttuneSelect)
            editor.putInt("combatWizSelect", combatWizSelect)
            editor.putInt("harvestSelect", harvestSelect)
            editor.putInt("morticianSelect", morticianSelect)
            editor.putInt("refocusSelect", refocusSelect)
            editor.putInt("spellParrySelect", spellParrySelect)
            editor.putInt("spellVersSkillSelect", spellVersSkillSelect)
            editor.putInt("spellSwitchSelect", spellSwitchSelect)
            editor.putString("sphereSelect1", sphereSelect1)
            editor.putString("sphereSelect2", sphereSelect2)
            editor.putString("sphereSelect3", sphereSelect3)
            editor.putInt("slot1Select", slot1Select)
            editor.putInt("slot2Select", slot2Select)
            editor.putInt("slot3Select", slot3Select)
            editor.putInt("slot4Select", slot4Select)
            editor.putInt("slot5Select", slot5Select)
            editor.putInt("slot6Select", slot6Select)
            editor.putInt("slot7Select", slot7Select)
            editor.putInt("slot8Select", slot8Select)
            editor.putInt("slot9Select", slot9Select)
            editor.putInt("ritualSelect", ritualSelect)

            editor.apply()
            editor.commit()

            sharedcharacterRace2 = sharedPreferences2.getString("characterRace", "Race")
            sharedcharacterClass2 = sharedPreferences2.getString("characterClass", "Class")
            sharedcharacterVocation2 = sharedPreferences2.getString("characterVocation", "Vocation")
            sharedblanketsInt2 = sharedPreferences2.getInt("blanketsInt", 0)
            if (sharedcharacterVocation2 != "Vocation"){
                profile2Name.text = "$sharedcharacterRace2\n$sharedcharacterVocation2\n$sharedblanketsInt2 Blankets"
            }
            else{
                profile2Name.text = "$sharedcharacterRace2\n$sharedcharacterClass2\n$sharedblanketsInt2 Blankets"
            }
        }

        profile2Load.setOnClickListener() {
            //Character Values
            val sharedcharacterRace = sharedPreferences2.getString("characterRace", characterRace)
            val sharedcultureFragsInt = sharedPreferences2.getInt("cultureFragsInt", cultureFragsInt)
            println("IN LOAD CULTURE IS $cultureFragsInt AND SHARED CULTURE IS $sharedcultureFragsInt")
            val sharedcharacterCulture = sharedPreferences2.getString("characterCulture", characterCulture)
            val sharedcharacterClass = sharedPreferences2.getString("characterClass", characterClass)
            println("IN LOAD CLASS IS $characterClass AND SHARED CLASS IS $sharedcharacterClass")
            val sharedcharacterVocation = sharedPreferences2.getString("characterVocation", characterVocation)
            println("IN LOAD VOCATION IS $characterVocation AND SHARED VOCATION IS $sharedcharacterVocation")
            val sharedlevelInt = sharedPreferences2.getInt("levelInt", levelInt)
            val sharedhpInt = sharedPreferences2.getInt("hpInt", hpInt)
            val sharedblanketsInt = sharedPreferences2.getInt("blanketsInt", blanketsInt)
            val sharedcpInt = sharedPreferences2.getInt("cpInt", cpInt)
            val sharedfreeInt = sharedPreferences2.getInt("freeInt", freeInt)
            val sharedcharacterSpentInt = sharedPreferences2.getInt("characterSpentInt", characterSpentInt)
            val sharedcharacterFragsInt = sharedPreferences2.getInt("characterFragsInt", characterFragsInt)

            //General Skills
            val sharedautoRacialSkill = sharedPreferences2.getString("autoRacialSkill", autoRacialSkill)
            val sharedracialSkill = sharedPreferences2.getString("racialSkill", racialSkill)
            val sharedracialSelect = sharedPreferences2.getInt("racialSelect", racialSelect)
            val sharedbodySelect = sharedPreferences2.getInt("bodySelect", bodySelect)
            val sharedstrengthSelect = sharedPreferences2.getInt("strengthSelect", strengthSelect)
            val sharedlevel3Skill = sharedPreferences2.getString("level3Skill", level3Skill)
            val sharedlevel3Select = sharedPreferences2.getInt("level3Select", level3Select)
            val sharedlevel6Skill = sharedPreferences2.getString("level6Skill", level6Skill)
            val sharedlevel6Select = sharedPreferences2.getInt("level6Select", level6Select)
            val sharedlevel9Skill = sharedPreferences2.getString("level9Skill", level9Skill)
            val sharedlevel9Select = sharedPreferences2.getInt("level9Select", level9Select)
            val sharedlevel12Skill = sharedPreferences2.getString("level12Skill", level12Skill)
            val sharedlevel12Select = sharedPreferences2.getInt("level12Select", level12Select)
            val sharedtrapsmithSelect = sharedPreferences2.getInt("trapsmithSelect", trapsmithSelect)
            val sharedtradesmanSelect = sharedPreferences2.getInt("tradesmanSelect", tradesmanSelect)
            val sharedalchemySelect = sharedPreferences2.getInt("alchemySelect", alchemySelect)
            val sharedchemistrySelect = sharedPreferences2.getInt("chemistrySelect", chemistrySelect)
            val sharedblacksmithingSelect = sharedPreferences2.getInt("blacksmithingSelect", blacksmithingSelect)
            val sharedartificeSelect = sharedPreferences2.getInt("artificeSelect", artificeSelect)
            val sharedscrollcraftingSelect = sharedPreferences2.getInt("scrollcraftingSelect", scrollcraftingSelect)
            val sharedcoldHandsSelect = sharedPreferences2.getInt("coldHandsSelect", coldHandsSelect)
            val sharedcreateAlcoholSelect = sharedPreferences2.getInt("createAlcoholSelect", createAlcoholSelect)
            val sharedheavyDrinkerSelect = sharedPreferences2.getInt("heavyDrinkerSelect", heavyDrinkerSelect)
            val sharedhindsightSelect = sharedPreferences2.getInt("hindsightSelect", hindsightSelect)
            val sharedintuitionSelect = sharedPreferences2.getInt("intuitionSelect", intuitionSelect)
            val sharedlootingSelect = sharedPreferences2.getInt("lootingSelect", lootingSelect)
            val sharedparagonSelect = sharedPreferences2.getInt("paragonSelect", paragonSelect)
            val sharedpossumSelect = sharedPreferences2.getInt("possumSelect", possumSelect)
            val sharedteacherSelect = sharedPreferences2.getInt("teacherSelect", teacherSelect)
            //Warrior Skills
            val sharedambidexteritySelect = sharedPreferences2.getInt("ambidexteritySelect", ambidexteritySelect)
            val sharedflorentineSelect = sharedPreferences2.getInt("florentineSelect", florentineSelect)
            val sharedflurrySelect = sharedPreferences2.getInt("flurrySelect", flurrySelect)
            val sharedheavyArmorSelect = sharedPreferences2.getInt("heavyArmorSelect", heavyArmorSelect)
            val sharedshieldSelect = sharedPreferences2.getInt("shieldSelect", shieldSelect)
            val sharedselfMutilateSelect = sharedPreferences2.getInt("selfMutilateSelect", selfMutilateSelect)
            val sharedweapRefocusSelect = sharedPreferences2.getInt("weapRefocusSelect", weapRefocusSelect)
            val sharedgroupProfMedSelect = sharedPreferences2.getInt("groupProfMedSelect", groupProfMedSelect)
            val sharedgroupProfLrgSelect = sharedPreferences2.getInt("groupProfLrgSelect", groupProfLrgSelect)
            val sharedprofExoticSelect = sharedPreferences2.getInt("profExoticSelect", profExoticSelect)
            val sharedgroupSpecSelect = sharedPreferences2.getInt("groupSpecSelect", groupSpecSelect)
            val sharedspecificSpecSelect = sharedPreferences2.getInt("specificSpecSelect", specificSpecSelect)
            val sharedslayParrySelect = sharedPreferences2.getInt("slayParrySelect", slayParrySelect)
            val sharedslayParryMstrSelect = sharedPreferences2.getInt("slayParryMstrSelect", slayParryMstrSelect)
            val sharedbattlefieldRepairSelect = sharedPreferences2.getInt("battlefieldRepairSelect", battlefieldRepairSelect)
            val sharedcrippleSelect = sharedPreferences2.getInt("crippleSelect", crippleSelect)
            val shareddecapitateSelect = sharedPreferences2.getInt("decapitateSelect", decapitateSelect)
            val shareddirtEyeSelect = sharedPreferences2.getInt("dirtEyeSelect", dirtEyeSelect)
            val sharedtripSelect = sharedPreferences2.getInt("tripSelect", tripSelect)
            val sharedwhirlBlowsSelect = sharedPreferences2.getInt("whirlBlowsSelect", whirlBlowsSelect)
            //Rogue Skills
            val sharedgarroteSelect = sharedPreferences2.getInt("garroteSelect", garroteSelect)
            val sharedsapSelect = sharedPreferences2.getInt("sapSelect", sapSelect)
            val sharedvitalBlowSelect = sharedPreferences2.getInt("vitalBlowSelect", vitalBlowSelect)
            val shareddodgeSelect = sharedPreferences2.getInt("dodgeSelect", dodgeSelect)
            val sharedspecificCritSelect = sharedPreferences2.getInt("specificCritSelect", specificCritSelect)
            val sharedgroupCritSelect = sharedPreferences2.getInt("groupCritSelect", groupCritSelect)
            val sharedexecuteSelect = sharedPreferences2.getInt("executeSelect", executeSelect)
            val sharedexecuteMstrSelect = sharedPreferences2.getInt("executeMstrSelect", executeMstrSelect)
            val sharedblindfighterSelect = sharedPreferences2.getInt("blindfighterSelect", blindfighterSelect)
            val sharedescapeSelect = sharedPreferences2.getInt("escapeSelect", escapeSelect)
            val sharedriposteSelect = sharedPreferences2.getInt("riposteSelect", riposteSelect)
            val sharedsuckerPunchSelect = sharedPreferences2.getInt("suckerPunchSelect", suckerPunchSelect)
            val sharedthievesCantSelect = sharedPreferences2.getInt("thievesCantSelect", thievesCantSelect)
            val sharedtumbleSelect = sharedPreferences2.getInt("tumbleSelect", tumbleSelect)
            //Scholar Skills
            val sharedmysticismSelect = sharedPreferences2.getInt("mysticismSelect", mysticismSelect)
            val shareddemAngArtsSelect = sharedPreferences2.getInt("demAngArtsSelect", demAngArtsSelect)
            val sharednecroArtsSelect = sharedPreferences2.getInt("necroArtsSelect", necroArtsSelect)
            val sharedanatomySelect = sharedPreferences2.getInt("anatomySelect", anatomySelect)
            val sharedfirstAidSelect = sharedPreferences2.getInt("firstAidSelect", firstAidSelect)
            val sharedphysicianSelect = sharedPreferences2.getInt("physicianSelect", physicianSelect)
            val sharedreadWriteSelect = sharedPreferences2.getInt("readWriteSelect", readWriteSelect)
            val sharedreadMagicSelect = sharedPreferences2.getInt("readMagicSelect", readMagicSelect)
            val sharedrdAdvMagicSelect = sharedPreferences2.getInt("rdAdvMagicSelect", rdAdvMagicSelect)
            val sharedrdRitualMagicSelect = sharedPreferences2.getInt("rdRitualMagicSelect", rdRitualMagicSelect)
            val sharedadvRitualSelect = sharedPreferences2.getInt("advRitualSelect", advRitualSelect)
            val sharedeleAttuneSelect = sharedPreferences2.getInt("eleAttuneSelect", eleAttuneSelect)
            val sharedcombatWizSelect = sharedPreferences2.getInt("combatWizSelect", combatWizSelect)
            val sharedharvestSelect = sharedPreferences2.getInt("harvestSelect", harvestSelect)
            val sharedmorticianSelect = sharedPreferences2.getInt("morticianSelect", morticianSelect)
            val sharedrefocusSelect = sharedPreferences2.getInt("refocusSelect", refocusSelect)
            val sharedspellParrySelect = sharedPreferences2.getInt("spellParrySelect", spellParrySelect)
            val sharedspellVersSkillSelect = sharedPreferences2.getInt("spellVersSkillSelect", spellVersSkillSelect)
            val sharedspellSwitchSelect = sharedPreferences2.getInt("spellSwitchSelect", spellSwitchSelect)
            val sharedsphereSelect1 = sharedPreferences2.getString("sphereSelect1", sphereSelect1)
            val sharedsphereSelect2 = sharedPreferences2.getString("sphereSelect2", sphereSelect2)
            val sharedsphereSelect3 = sharedPreferences2.getString("sphereSelect3", sphereSelect3)
            val sharedslot1Select = sharedPreferences2.getInt("slot1Select", slot1Select)
            val sharedslot2Select = sharedPreferences2.getInt("slot2Select", slot2Select)
            val sharedslot3Select = sharedPreferences2.getInt("slot3Select", slot3Select)
            val sharedslot4Select = sharedPreferences2.getInt("slot4Select", slot4Select)
            val sharedslot5Select = sharedPreferences2.getInt("slot5Select", slot5Select)
            val sharedslot6Select = sharedPreferences2.getInt("slot6Select", slot6Select)
            val sharedslot7Select = sharedPreferences2.getInt("slot7Select", slot7Select)
            val sharedslot8Select = sharedPreferences2.getInt("slot8Select", slot8Select)
            val sharedslot9Select = sharedPreferences2.getInt("slot9Select", slot9Select)
            val sharedritualSelect = sharedPreferences2.getInt("ritualSelect", ritualSelect)

            val intent = Intent(this, MainActivity::class.java)
            intent.putExtra("characterRace", sharedcharacterRace)
            intent.putExtra("characterCulture", sharedcharacterCulture)
            intent.putExtra("cultureFragsInt", sharedcultureFragsInt)
            intent.putExtra("characterClass", sharedcharacterClass)
            intent.putExtra("characterVocation", sharedcharacterVocation)
            intent.putExtra("levelInt", sharedlevelInt)
            intent.putExtra("hpInt", sharedhpInt)
            intent.putExtra("blanketsInt", sharedblanketsInt)
            intent.putExtra("cpInt", sharedcpInt)
            intent.putExtra("freeInt", sharedfreeInt)
            intent.putExtra("characterSpentInt", sharedcharacterSpentInt)
            intent.putExtra("characterFragsInt", sharedcharacterFragsInt)

            //General Skills
            intent.putExtra("level3Skill", sharedlevel3Skill)
            intent.putExtra("level3Select", sharedlevel3Select)
            intent.putExtra("level6Skill", sharedlevel6Skill)
            intent.putExtra("level6Select", sharedlevel6Select)
            intent.putExtra("level9Skill", sharedlevel9Skill)
            intent.putExtra("level9Select", sharedlevel9Select)
            intent.putExtra("level12Skill", sharedlevel12Skill)
            intent.putExtra("level12Select", sharedlevel12Select)
            intent.putExtra("autoRacialSkill", sharedautoRacialSkill)
            intent.putExtra("racialSkill", sharedracialSkill)
            intent.putExtra("racialSelect", sharedracialSelect)
            intent.putExtra("bodySelect", sharedbodySelect)
            intent.putExtra("strengthSelect", sharedstrengthSelect)
            intent.putExtra("trapsmithSelect", sharedtrapsmithSelect)
            intent.putExtra("tradesmanSelect", sharedtradesmanSelect)
            intent.putExtra("alchemySelect", sharedalchemySelect)
            intent.putExtra("chemistrySelect", sharedchemistrySelect)
            intent.putExtra("blacksmithingSelect", sharedblacksmithingSelect)
            intent.putExtra("artificeSelect", sharedartificeSelect)
            intent.putExtra("scrollcraftingSelect", sharedscrollcraftingSelect)
            intent.putExtra("coldHandsSelect", sharedcoldHandsSelect)
            intent.putExtra("createAlcoholSelect", sharedcreateAlcoholSelect)
            intent.putExtra("heavyDrinkerSelect", sharedheavyDrinkerSelect)
            intent.putExtra("hindsightSelect", sharedhindsightSelect)
            intent.putExtra("intuitionSelect", sharedintuitionSelect)
            intent.putExtra("lootingSelect", sharedlootingSelect)
            intent.putExtra("paragonSelect", sharedparagonSelect)
            intent.putExtra("possumSelect", sharedpossumSelect)
            intent.putExtra("teacherSelect", sharedteacherSelect)
            //Warrior Skills
            intent.putExtra("ambidexteritySelect", sharedambidexteritySelect)
            intent.putExtra("florentineSelect", sharedflorentineSelect)
            intent.putExtra("flurrySelect", sharedflurrySelect)
            intent.putExtra("heavyArmorSelect", sharedheavyArmorSelect)
            intent.putExtra("shieldSelect", sharedshieldSelect)
            intent.putExtra("selfMutilateSelect", sharedselfMutilateSelect)
            intent.putExtra("weapRefocusSelect", sharedweapRefocusSelect)
            intent.putExtra("groupProfMedSelect", sharedgroupProfMedSelect)
            intent.putExtra("groupProfLrgSelect", sharedgroupProfLrgSelect)
            intent.putExtra("profExoticSelect", sharedprofExoticSelect)
            intent.putExtra("groupSpecSelect", sharedgroupSpecSelect)
            intent.putExtra("specificSpecSelect", sharedspecificSpecSelect)
            intent.putExtra("slayParrySelect", sharedslayParrySelect)
            intent.putExtra("slayParryMstrSelect", sharedslayParryMstrSelect)
            intent.putExtra("battlefieldRepairSelect", sharedbattlefieldRepairSelect)
            intent.putExtra("crippleSelect", sharedcrippleSelect)
            intent.putExtra("decapitateSelect", shareddecapitateSelect)
            intent.putExtra("dirtEyeSelect", shareddirtEyeSelect)
            intent.putExtra("tripSelect", sharedtripSelect)
            intent.putExtra("whirlBlowsSelect", sharedwhirlBlowsSelect)
            //Rogue Skills
            intent.putExtra("garroteSelect", sharedgarroteSelect)
            intent.putExtra("sapSelect", sharedsapSelect)
            intent.putExtra("vitalBlowSelect", sharedvitalBlowSelect)
            intent.putExtra("dodgeSelect", shareddodgeSelect)
            intent.putExtra("specificCritSelect", sharedspecificCritSelect)
            intent.putExtra("groupCritSelect", sharedgroupCritSelect)
            intent.putExtra("executeSelect", sharedexecuteSelect)
            intent.putExtra("executeMstrSelect", sharedexecuteMstrSelect)
            intent.putExtra("blindfighterSelect", sharedblindfighterSelect)
            intent.putExtra("escapeSelect", sharedescapeSelect)
            intent.putExtra("riposteSelect", sharedriposteSelect)
            intent.putExtra("suckerPunchSelect", sharedsuckerPunchSelect)
            intent.putExtra("thievesCantSelect", sharedthievesCantSelect)
            intent.putExtra("tumbleSelect", sharedtumbleSelect)
            //Scholar Skills
            intent.putExtra("mysticismSelect", sharedmysticismSelect)
            intent.putExtra("demAngArtsSelect", shareddemAngArtsSelect)
            intent.putExtra("necroArtsSelect", sharednecroArtsSelect)
            intent.putExtra("anatomySelect", sharedanatomySelect)
            intent.putExtra("firstAidSelect", sharedfirstAidSelect)
            intent.putExtra("physicianSelect", sharedphysicianSelect)
            intent.putExtra("readWriteSelect", sharedreadWriteSelect)
            intent.putExtra("readMagicSelect", sharedreadMagicSelect)
            intent.putExtra("rdAdvMagicSelect", sharedrdAdvMagicSelect)
            intent.putExtra("rdRitualMagicSelect", sharedrdRitualMagicSelect)
            intent.putExtra("advRitualSelect", sharedadvRitualSelect)
            intent.putExtra("eleAttuneSelect", sharedeleAttuneSelect)
            intent.putExtra("combatWizSelect", sharedcombatWizSelect)
            intent.putExtra("harvestSelect", sharedharvestSelect)
            intent.putExtra("morticianSelect", sharedmorticianSelect)
            intent.putExtra("refocusSelect", sharedrefocusSelect)
            intent.putExtra("spellParrySelect", sharedspellParrySelect)
            intent.putExtra("spellVersSkillSelect", sharedspellVersSkillSelect)
            intent.putExtra("spellSwitchSelect", sharedspellSwitchSelect)
            intent.putExtra("sphereSelect1", sharedsphereSelect1)
            intent.putExtra("sphereSelect2", sharedsphereSelect2)
            intent.putExtra("sphereSelect3", sharedsphereSelect3)
            intent.putExtra("slot1Select", sharedslot1Select)
            intent.putExtra("slot2Select", sharedslot2Select)
            intent.putExtra("slot3Select", sharedslot3Select)
            intent.putExtra("slot4Select", sharedslot4Select)
            intent.putExtra("slot5Select", sharedslot5Select)
            intent.putExtra("slot6Select", sharedslot6Select)
            intent.putExtra("slot7Select", sharedslot7Select)
            intent.putExtra("slot8Select", sharedslot8Select)
            intent.putExtra("slot9Select", sharedslot9Select)
            intent.putExtra("ritualSelect", sharedritualSelect)

            startActivity(intent)
        }

        profile2Delete.setOnClickListener() {
            profile2Name.text = "Race\nClass\n0 Blankets"

            val editor = sharedPreferences2.edit()
            editor.clear()
            editor.apply()
        }













        closePopup.setOnClickListener() {
            onBackPressed()
        }
    }

    override fun onBackPressed() {
        finish()
    }

}